# Generated by Django 5.1.1 on 2024-09-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikeshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('product_image', models.FileField(upload_to='products')),
            ],
        ),
    ]
